version: '3'
services:
  mongo:
    restart: always
    image: 'mongo'
    ports:
      - '27017:27017'
  redis:
    restart: always
    image: 'redis'
    ports:
      - '6379:6379'
  backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGO_HOSTNAME=mongo
      - MONGO_PORT=27017
      - MONGO_DB=mongo
    depends_on:
      - redis
      - mongo
  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    volumes:
      - /app/node_modules
      - ./frontend:/app
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
    stdin_open: true
    tty: true
    depends_on:
      - frontend
      - backend
